### PR TITLE
mapValues

### PR DESCRIPTION
**Pull request by rpearce**
_API docs & test should be good at explaining what this is._

### CODE REVIEW

**Comment by mgreystone** [comment]
I might be missing something, but [`R.map` maps over object values already.](https://ramdajs.com/repl/#?map%28omit%28%5B%20%27a%27%20%5D%29%2C%20%7B%0A%20%20foo%3A%20%7B%20a%3A%201%2C%20b%3A%202%2C%20c%3A%203%20%7D%2C%0A%20%20bar%3A%20%7B%20a%3A%204%2C%20b%3A%205%2C%20c%3A%206%20%7D%2C%0A%7D%29)

**Comment by rpearce** [comment]
@mgreystone o_O

**Comment by rpearce** [comment]
son of a ...

**Comment by flintinatux** [comment]
@rpearce, don't feel bad:  I think Ramda's overloaded `map` is unexpected, too.  Which is why I made a separate [`mapObj` in `tinyfunk`](https://github.com/flintinatux/tinyfunk/blob/master/src.js#L161-L166), similar to your `mapValues`.

**Comment by evilsoft** [comment]
@rpearce also crocks map will map over an object

**Comment by rpearce** [comment]
Thanks for making me feel better :)

Also, I like `tinyfunk`!

**Pull request closed without merging**
